name: MySQL Database 

on: 
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout main branch from Github
        uses: actions/checkout@v3
        
      - name: Shutdown Ubuntu MySQL (SUDO)
        run: sudo service mysql stop
      
      - uses: mirromutth/mysql-action@v1.1
        with:
         host port: 3306 # Optional, default value is 3306. The port of host
         container port: 3306 # Optional, default value is 3306. The port of container
         character set server: 'utf8' # Optional, default value is 'utf8mb4'. The '--character-set-server' option for mysqld
         collation server: 'utf8_general_ci' # Optional, default value is 'utf8mb4_general_ci'. The '--collation-server' option for mysqld
         mysql version: '8.0' # Optional, default value is "latest". The version of the MySQL
         mysql database: 'some_test' # Optional, default value is "test". The specified database which will be create
         mysql root password: ${{ secrets.JDBC_PASSWORD }} # Required if "mysql user" is empty, default is empty. The root superuser password
         mysql user: ${{ secrets.JDBC_USER }} # Required if "mysql root password" is empty, default is empty. The superuser for the specified database. Can use secrets, too
         mysql password: ${{ secrets.JDBC_PASSWORD }} # Required if "mysql user" exists. The password for the "mysql user"
      
      - name: Build the Docker image
        run: docker build . --build-arg ${{ secrets.JDBC_PASSWORD }} --file Dockerfile --tag ca1-db
      - run: docker run -p 3306:3306 ca1-db
      
