name: MySQL Database 

on: 
  push:
    branches: [ main ]
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Create env file
        run: |
          echo "${{ secrets.ENV_SECRETS }}" > .env
          
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: whoami
        
      - name: Checkout main branch from Github
        uses: actions/checkout@v3
      
      - name: Build the Docker image
        run: docker build . --build-arg ${{ secrets.JDBC_PASSWORD }} --file Dockerfile --tag ca1-db
      - run: docker run -p 3306:3306 ca1-db
